- name: Creates {{ job }}-{{ set }}
  file: path={{ idcm_install_path }}/{{ job }} state=directory
- name: install {{ job }}-{{ set }}
  synchronize: "src={{ idcw_code_path }}/{{ set }}/{{ job }}/ dest={{ idcm_install_path }}/{{ job }}/"
- name: revise group 
  shell: cd {{ idcm_install_path }} && chown -R root:root {{ job }}
- name: restart {{ job }}
  shell: supervisorctl restart {{ job }}
